author: Gerald S Brown
facebook: "https://facebook.com/example"
twitter: "https://twitter.com/example"
email: "gbrown@gerbreown.com""
name: "GerBreOwn Publishing/Software"
location: Philippines
phone: (999) 999-9999
hours: "**Mon-Fri:** 9:00AM - 6:00PM, ET"
