baseurl: https://www.gsb-wx.me
languageCode: en-us
title: My Weather Site
# theme: hugo-theme-learn
theme: eclectic

publish_date: true
last_modified: true
enableGitInfo: true
#{{ dateFormat "Jan 24, 1943 00:00:00" .Date.Local }}
menu:                                         # Menu placement
  main:                                       #    - Name of the menu
    - identifier: about                       #       - Identifier
      name: About                             #       - Display name (theme specific key)
      url: /about                             #       - Target URL
      weight: 1                               #       - Sorting order
    - identifier: contact
      name: Contact
      url: /contact
      weight: 2
params:                                       # Theme specific parameters
  color: "#71B180"
  copyright: "Copyright &copy; 2020 Acme Corporation. All Rights Reserved."
  footer:
    - title: About
      content: Acme Corporation is the world's leading manufacturer of digital shapes. From squares and circles to triangles and hexagons, we have it all. Browse through our collection of various forms with different thickness and line styles. We shape the world. You live in it.
    - title: Recent Blog Posts
      recents: blog
      recentCount: 7
    - title: Contact Us
      contact: true
