color: "#71B180"
copyright: "Copyright &copy; 2021 GerBreOwn Publishing/Software. All Rights Reserved."
footer:
  - title: Important Links
  - title: Recent Blog Posts
    recents: blog
    recentCount: 7
  - title: Contact Us
    contact: true
style: green
logo: /image/logo.png
logo_small: /image/logo.png
menu: true
