baseurl: https://www.gsb-wx.me
languageCode: en-us
title: My Weather Site
theme: hugo-theme-learn
author: Gerald S Brown
publish_date: true
last_modified: true
enableGitInfo: true
{{ dateFormat "Jan 24, 1943 00:00:00" .Date.Local }}

